services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "cosmdb_lb2"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      RUN_AS_ROOT: "true"
    shm_size: 1gb
    volumes:
#      - ./postgres/SQL:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - postgres_net
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    ports:
      - "5532:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    networks:
      - postgres_net
    depends_on:
      - postgres
networks:
  postgres_net:
    driver: bridge