-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id serial NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_contact_info character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    order_customer_id integer NOT NULL,
    order_create_date date NOT NULL,
    order_total_amount integer NOT NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    product_id serial NOT NULL,
    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    product_category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_season_id integer NOT NULL,
    product_supplier_id integer NOT NULL,
    PRIMARY KEY (product_id)
);

ALTER TABLE IF EXISTS public.products
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.seasons
(
    season_id serial NOT NULL,
    season_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    season_start_date date NOT NULL,
    season_end_date date NOT NULL,
    PRIMARY KEY (season_id)
);

CREATE TABLE IF NOT EXISTS public.suppliers
(
    supplier_id serial NOT NULL,
    supplier_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    supplier_contact_info character varying(255) COLLATE pg_catalog."default",
    supplier_address character varying(255) COLLATE pg_catalog."default",
    PRIMARY KEY (supplier_id)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    orders_order_id serial NOT NULL,
    products_product_id serial NOT NULL,
    order_detail_quantity integer NOT NULL,
    order_detail_price integer NOT NULL
);

ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (order_customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (product_season_id)
    REFERENCES public.seasons (season_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (product_supplier_id)
    REFERENCES public.suppliers (supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_details
    ADD FOREIGN KEY (orders_order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_details
    ADD FOREIGN KEY (products_product_id)
    REFERENCES public.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;