-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."HubCustomers"
(
    hub_customer_customer_id serial NOT NULL,
    hub_customer_load_datetime timestamp with time zone NOT NULL,
    hub_customer_record_source text,
    PRIMARY KEY (hub_customer_customer_id)
);

CREATE TABLE IF NOT EXISTS public."HubProducts"
(
    hub_products_product_id serial NOT NULL,
    hub_products_load_datetime timestamp with time zone NOT NULL,
    hub_products_record_source text,
    PRIMARY KEY (hub_products_product_id)
);

CREATE TABLE IF NOT EXISTS public."HubSeasons"
(
    hub_seasons_season_id serial NOT NULL,
    hub_seasons_load_datetime timestamp with time zone NOT NULL,
    hub_seasons_record_source text,
    PRIMARY KEY (hub_seasons_season_id)
);

CREATE TABLE IF NOT EXISTS public."HubOrders"
(
    hub_orders_order_id serial NOT NULL,
    hub_orders_load_datetime timestamp with time zone NOT NULL,
    hub_orders_record_source text,
    PRIMARY KEY (hub_orders_order_id)
);

CREATE TABLE IF NOT EXISTS public."HubSuppliers"
(
    hub_suppliers_supplier_id serial NOT NULL,
    hub_suppliers_load_datetime timestamp with time zone NOT NULL,
    hub_suppliers_record_source text,
    PRIMARY KEY (hub_suppliers_supplier_id)
);

CREATE TABLE IF NOT EXISTS public."LinkCustomerOrders"
(
    "HubOrders_hub_orders_order_id" serial NOT NULL,
    "HubCustomers_hub_customer_customer_id" serial NOT NULL,
    link_customer_orders_load_datetime timestamp with time zone NOT NULL,
    link_customer_orders_record_source text
);

CREATE TABLE IF NOT EXISTS public."LinkProductSuppliers"
(
    "HubProducts_hub_products_product_id" serial NOT NULL,
    "HubSuppliers_hub_suppliers_supplier_id" serial NOT NULL,
    link_product_suppliers_load_datetime timestamp with time zone NOT NULL,
    link_product_suppliers_record_source text
);

CREATE TABLE IF NOT EXISTS public."SatCustomers"
(
    sat_customers_customer_id serial NOT NULL,
    sat_customers_customer_name text NOT NULL,
    sat_customers_contact_info text NOT NULL,
    sat_customers_address text NOT NULL,
    sat_customers_load_datetime timestamp with time zone NOT NULL,
    sat_customers_record_source text
);

CREATE TABLE IF NOT EXISTS public."SatProducts"
(
    sat_products_product_id serial NOT NULL,
    sat_products_product_name text NOT NULL,
    sat_products_product_category text NOT NULL,
    sat_products_price integer NOT NULL,
    sat_products_load_datetime timestamp with time zone NOT NULL,
    sat_products_record_source text
);

CREATE TABLE IF NOT EXISTS public."SatSuppliers"
(
    sat_suppliers_supplier_id serial NOT NULL,
    sat_suppliers_supplier_name text NOT NULL,
    sat_suppliers_contact_info text NOT NULL,
    sat_suppliers_address text NOT NULL,
    sat_suppliers_load_datetime timestamp with time zone NOT NULL,
    sat_suppliers_record_source text
);

CREATE TABLE IF NOT EXISTS public."SatOrders"
(
    sat_orders_order_id serial NOT NULL,
    sat_orders_order_create_date date NOT NULL,
    sat_orders_order_total_amount integer NOT NULL,
    sat_orders_load_datetime timestamp with time zone NOT NULL,
    sat_orders_record_source text
);

CREATE TABLE IF NOT EXISTS public."SatOrderDetails"
(
    sat_order_details_id serial NOT NULL,
    sat_order_details_order_detail_quantity integer NOT NULL,
    sat_order_details_order_detail_price integer NOT NULL,
    sat_order_details_load_datetime timestamp with time zone NOT NULL,
    sat_order_details_record_source text
);

CREATE TABLE IF NOT EXISTS public."SatSeasons"
(
    sat_seasons_season_id integer NOT NULL,
    sat_seasons_season_name text NOT NULL,
    sat_seasons_season_start_date daterange NOT NULL,
    sat_seasons_season_end_date daterange NOT NULL,
    sat_seasons_load_datetime timestamp with time zone NOT NULL,
    sat_seasons_record_source text
);

CREATE TABLE IF NOT EXISTS public."LinkProductSeasons"
(
    "HubProducts_hub_products_product_id" serial NOT NULL,
    "HubSeasons_hub_seasons_season_id" serial NOT NULL,
    link_product_seasons_load_datetime timestamp with time zone NOT NULL,
    link_product_seasons_record_source text
);

CREATE TABLE IF NOT EXISTS public."LinkProductOrders"
(
    link_product_orders_id serial NOT NULL,
    "HubOrders_hub_orders_order_id" serial NOT NULL,
    "HubProducts_hub_products_product_id" serial NOT NULL,
    link_order_details_load_datetime timestamp with time zone NOT NULL,
    link_order_details_record_source text,
    PRIMARY KEY (link_product_orders_id)
);

ALTER TABLE IF EXISTS public."LinkCustomerOrders"
    ADD FOREIGN KEY ("HubOrders_hub_orders_order_id")
    REFERENCES public."HubOrders" (hub_orders_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkCustomerOrders"
    ADD FOREIGN KEY ("HubCustomers_hub_customer_customer_id")
    REFERENCES public."HubCustomers" (hub_customer_customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkProductSuppliers"
    ADD FOREIGN KEY ("HubProducts_hub_products_product_id")
    REFERENCES public."HubProducts" (hub_products_product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkProductSuppliers"
    ADD FOREIGN KEY ("HubSuppliers_hub_suppliers_supplier_id")
    REFERENCES public."HubSuppliers" (hub_suppliers_supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatCustomers"
    ADD FOREIGN KEY (sat_customers_customer_id)
    REFERENCES public."HubCustomers" (hub_customer_customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatProducts"
    ADD FOREIGN KEY (sat_products_product_id)
    REFERENCES public."HubProducts" (hub_products_product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatSuppliers"
    ADD FOREIGN KEY (sat_suppliers_supplier_id)
    REFERENCES public."HubSuppliers" (hub_suppliers_supplier_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatOrders"
    ADD FOREIGN KEY (sat_orders_order_id)
    REFERENCES public."HubOrders" (hub_orders_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatOrderDetails"
    ADD FOREIGN KEY (sat_order_details_id)
    REFERENCES public."LinkProductOrders" (link_product_orders_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SatSeasons"
    ADD FOREIGN KEY (sat_seasons_season_id)
    REFERENCES public."HubSeasons" (hub_seasons_season_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkProductSeasons"
    ADD FOREIGN KEY ("HubProducts_hub_products_product_id")
    REFERENCES public."HubProducts" (hub_products_product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkProductSeasons"
    ADD FOREIGN KEY ("HubSeasons_hub_seasons_season_id")
    REFERENCES public."HubSeasons" (hub_seasons_season_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkProductOrders"
    ADD FOREIGN KEY ("HubOrders_hub_orders_order_id")
    REFERENCES public."HubOrders" (hub_orders_order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."LinkProductOrders"
    ADD FOREIGN KEY ("HubProducts_hub_products_product_id")
    REFERENCES public."HubProducts" (hub_products_product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;